<?php
// One place for all product data — every page pulls from here by id.
$products = [

	// ===== MEN =====
	1 => [
		'category' => 'men',
		'name' => 'Classic Tee',
		'price' => 24.99,
		'img' => 'men/men1.jpg',
		'color' => 'Black',
		'sizes' => ['S', 'M', 'L', 'XL'],
		'details' => '100% cotton crewneck tee with a relaxed fit and soft hand-feel. Pre-shrunk fabric, ribbed collar, and reinforced stitching for everyday wear.',
	],
	2 => [
		'category' => 'men',
		'name' => 'Denim Jacket',
		'price' => 59.99,
		'img' => 'men/men2.jpg',
		'color' => 'Indigo Wash',
		'sizes' => ['S', 'M', 'L', 'XL'],
		'details' => 'Classic trucker-style denim jacket with a slightly worn wash, button-front closure, and two chest pockets. Layers easily over any outfit.',
	],
	3 => [
		'category' => 'men',
		'name' => 'Cargo Pants',
		'price' => 44.99,
		'img' => 'men/men3.jpg',
		'color' => 'Olive Green',
		'sizes' => ['30', '32', '34', '36'],
		'details' => 'Durable cotton-twill cargo pants with side utility pockets and an adjustable waistband. Built for comfort with a straight, relaxed leg.',
	],
	4 => [
		'category' => 'men',
		'name' => 'Hoodie',
		'price' => 39.99,
		'img' => 'men/men4.jpg',
		'color' => 'Charcoal Gray',
		'sizes' => ['S', 'M', 'L', 'XL'],
		'details' => 'Heavyweight fleece pullover hoodie with a kangaroo pocket, ribbed cuffs, and an adjustable drawstring hood. Soft on the inside, built to last.',
	],
	5 => [
		'category' => 'men',
		'name' => 'Chino Shorts',
		'price' => 29.99,
		'img' => 'men/men5.jpg',
		'color' => 'Beige',
		'sizes' => ['30', '32', '34', '36'],
		'details' => 'Lightweight cotton chino shorts with a clean, pressed look. Side and back pockets, mid-length cut, perfect for warm-weather days.',
	],
	6 => [
		'category' => 'men',
		'name' => 'Bomber Jacket',
		'price' => 69.99,
		'img' => 'men/men6.jpg',
		'color' => 'Black',
		'sizes' => ['S', 'M', 'L', 'XL'],
		'details' => 'Satin-finish bomber jacket with a ribbed collar, cuffs, and hem. Full front zip, side pockets, and a sleek silhouette for everyday layering.',
	],

	// ===== WOMEN =====
	7 => [
		'category' => 'women',
		'name' => 'Black Boots',
		'price' => 49.99,
		'img' => 'women/women1.jpg',
		'color' => 'Black',
		'sizes' => ['XS', 'S', 'M', 'L'],
		'details' => 'Pair of black leather ankle boots with a low block heel, positioned side by side at a slight three-quarter angle facing forward, smooth leather texture with a subtle sheen catching the studio light, clean stitching detail visible along the sole, centered composition on the light gray backdrop with a soft shadow beneath each boot.',
	],
	8 => [
		'category' => 'women',
		'name' => 'Black Coat',
		'price' => 34.99,
		'img' => 'women/women2.jpg',
		'color' => 'Black',
		'sizes' => ['XS', 'S', 'M', 'L'],
		'details' => 'Relaxed-fit linen black Coat with a button-front. Breathable fabric, perfect for layering or wearing.',
	],
	9 => [
		'category' => 'women',
		'name' => 'High-Waist Jeans',
		'price' => 54.99,
		'img' => 'women/women3.jpg',
		'color' => 'Medium Blue',
		'sizes' => ['24', '26', '28', '30'],
		'details' => 'High-waisted denim jeans with a slim straight leg and a touch of stretch for comfort. A timeless everyday staple.',
	],
	10 => [
		'category' => 'women',
		'name' => 'Knit Cardigan',
		'price' => 44.99,
		'img' => 'women/women4.jpg',
		'color' => 'Cream',
		'sizes' => ['XS', 'S', 'M', 'L'],
		'details' => 'Open-front chunky knit cardigan with ribbed cuffs and hem. Warm, cozy, and easy to throw on over any outfit.',
	],
	11 => [
		'category' => 'women',
		'name' => 'White t-shirt',
		'price' => 39.99,
		'img' => 'women/women5.jpg',
		'color' => 'Black',
		'sizes' => ['XS', 'S', 'M', 'L'],
		'details' => 'White linen t-shirt, relaxed fit with visible button placket down the front, pocket detail, slightly textured linen weave visible in the fabric, sleeves smoothed out symmetrically, overhead flat lay.',
	],
	12 => [
		'category' => 'women',
		'name' => 'Tailored Suit',
		'price' => 64.99,
		'img' => 'women/women6.jpg',
		'color' => 'Black',
		'sizes' => ['XS', 'S', 'M', 'L'],
		'details' => 'Full-suit tailored with structured shoulders and a fitted waist. A sharp layer for work or a night out.',
	],

	// ===== KIDS =====
	14 => [
		'category' => 'kids',
		'name' => 'Graphic Tee',
		'price' => 14.99,
		'img' => 'kids/kids1.jpg',
		'color' => 'White',
		'sizes' => ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
		'details' => 'Soft cotton t-shirt with a simple, fun print. Durable enough for playtime, easy to wash and wear again.',
	],
	15 => [
		'category' => 'kids',
		'name' => 'Joggers',
		'price' => 19.99,
		'img' => 'kids/kids2.jpg',
		'color' => 'Gray',
		'sizes' => ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
		'details' => 'Cotton-fleece jogger pants with an elastic waistband and cuffed ankles. Comfortable stretch for all-day movement.',
	],
	16 => [
		'category' => 'kids',
		'name' => 'Puffer Vest',
		'price' => 29.99,
		'img' => 'kids/kids3.jpg',
		'color' => 'Navy Blue',
		'sizes' => ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
		'details' => 'Lightweight quilted puffer vest with a full front zip. Warm layering piece, easy to move around in.',
	],
	17 => [
		'category' => 'kids',
		'name' => 'Denim Overalls',
		'price' => 27.99,
		'img' => 'kids/kids4.jpg',
		'color' => 'Light Blue',
		'sizes' => ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
		'details' => 'Classic denim overalls with adjustable shoulder straps and a front bib pocket. Durable and easy to layer over a tee.',
	],
	18 => [
		'category' => 'kids',
		'name' => 'Hooded Sweatshirt',
		'price' => 22.99,
		'img' => 'kids/kids5.jpg',
		'color' => 'Red',
		'sizes' => ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
		'details' => 'Soft pullover hoodie with a kangaroo pocket and ribbed cuffs. Warm, comfortable, and built for everyday adventures.',
	],
	19 => [
		'category' => 'kids',
		'name' => 'Sneakers',
		'price' => 34.99,
		'img' => 'kids/kids6.jpg',
		'color' => 'White',
		'sizes' => ['10C', '11C', '12C', '13C', '1Y'],
		'details' => 'Lightweight low-top sneakers with a cushioned sole and easy velcro closure. Built for running around all day.',
	],

	// ===== BEAUTY =====
	20 => [
		'category' => 'beauty',
		'name' => 'Hydrating Moisturizer',
		'price' => 22.99,
		'img' => 'beauty/beauty1.jpg',
		'color' => 'Fragrance-Free',
		'sizes' => ['30ml', '50ml', '100ml'],
		'details' => 'Lightweight daily moisturizer that hydrates without feeling heavy. Suitable for all skin types, fragrance-free formula.',
	],
	21 => [
		'category' => 'beauty',
		'name' => 'Matte Lipstick',
		'price' => 16.99,
		'img' => 'beauty/beauty2.jpg',
		'color' => 'Classic Red',
		'sizes' => ['Standard'],
		'details' => 'Long-wearing matte lipstick with full-coverage color in one swipe. Comfortable, non-drying formula.',
	],
	22 => [
		'category' => 'beauty',
		'name' => 'Signature Perfume',
		'price' => 49.99,
		'img' => 'beauty/beauty3.jpg',
		'color' => 'Warm Amber',
		'sizes' => ['30ml', '50ml', '100ml'],
		'details' => 'A warm, signature scent with notes of amber and soft musk. Long-lasting wear from morning to night.',
	],
	23 => [
		'category' => 'beauty',
		'name' => 'Vitamin C Serum',
		'price' => 27.99,
		'img' => 'beauty/beauty4.jpg',
		'color' => 'Brightening',
		'sizes' => ['15ml', '30ml'],
		'details' => 'Brightening vitamin C serum that helps even skin tone and add radiance. Lightweight, fast-absorbing formula.',
	],
	24 => [
		'category' => 'beauty',
		'name' => 'Foundation',
		'price' => 24.99,
		'img' => 'beauty/beauty5.jpg',
		'color' => 'Natural Beige',
		'sizes' => ['30ml'],
		'details' => 'Buildable, natural-finish foundation that evens out skin tone while letting your skin breathe. Lightweight all-day wear.',
	],
	25 => [
		'category' => 'beauty',
		'name' => 'Body Lotion',
		'price' => 18.99,
		'img' => 'beauty/beauty6.jpg',
		'color' => 'Fragrance-Free',
		'sizes' => ['100ml', '200ml'],
		'details' => 'Fast-absorbing body lotion that leaves skin soft and hydrated without a greasy feel. Daily use, all skin types.',
	],

];